#!/bin/sh -x

influx <<-EOSQL
CREATE DATABASE "jmeter" WITH DURATION INF REPLICATION 1 SHARD DURATION 1h NAME "autogen";
CREATE DATABASE "jmeter1" WITH DURATION INF REPLICATION 1 SHARD DURATION 1h NAME "autogen";
CREATE DATABASE "jmeter1000" WITH DURATION INF REPLICATION 1 SHARD DURATION 1h NAME "autogen";
CREATE DATABASE "jmeter10000" WITH DURATION INF REPLICATION 1 SHARD DURATION 1h NAME "autogen";
CREATE DATABASE "jmeter100000" WITH DURATION INF REPLICATION 1 SHARD DURATION 1h NAME "autogen";
EOSQL
